- name: Mercurial checkout of phabricator-qa-dev repo
  hg:
    repo: https://hg.mozilla.org/automation/phabricator-qa-dev
    dest: /home/phab/phabricator-qa-dev

- name: Copy dotfiles
  copy:
    src: /ansible/dotfiles/{{ item }}
    dest: /home/phab
    owner: phab
    group: phab
    mode: 0644
  with_items:
    - .bashrc
    - .gitconfig
    - .hgrc
    - .moz-phab-config

- name: Chown all home dir files to phab.phab
  file:
    dest: /home/phab
    owner: phab
    group: phab
    recurse: yes
