- name: Git checkout cinnabarc
  git:
    repo: https://github.com/mozilla-conduit/arcanist.git
    dest: /home/phab/.mozbuild/cinnabarc

- name: Git checkout and install git-cinnabar
  shell: |
    git clone https://github.com/glandium/git-cinnabar.git --branch master --single-branch /home/phab/.mozbuild/git-cinnabar
    export PATH=/home/phab/.mozbuild/git-cinnabar:$PATH
    cd /home/phab/.mozbuild/git-cinnabar && git cinnabar download

- name: Mercurial checkout of phabricator-qa-dev repo
  hg:
    repo: https://hg.mozilla.org/automation/phabricator-qa-dev
    dest: /home/phab/phabricator-qa-dev

- name: Mercurial checkout of phabricator-qa-dev using git-cinnabar wrapper
  shell: PATH=/home/phab/.mozbuild/git-cinnabar:$PATH git clone hg::https://hg.mozilla.org/automation/phabricator-qa-dev /home/phab/phabricator-qa-dev-cinnabar

- name: Checkout moz-phab code review wrapper
  pip:
    name: mozphab

- name: Copy dotfiles
  copy:
    src: /ansible/dotfiles/{{ item }}
    dest: /home/phab
    owner: phab
    group: phab
    mode: 0644
  with_items:
    - .bashrc
    - .gitconfig
    - .hgrc
    - .moz-phab-config

- name: Chown all home dir files to phab.phab
  file:
    dest: /home/phab
    owner: phab
    group: phab
    recurse: yes
