- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - diffutils
      - git
      - jq
      - mercurial
      - php
      - php-curl
      - php-json
      - python3
      - python3-pip
      - vim
      - xz

- name: Install moz-phab
  pip:
    name: MozPhab
