- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - mercurial
      - php
      - php-curl
      - php-json
      - python3
      - python3-pip
      - vim
      - xz
