- name: create user 'phab'
  user:
    name: phab
    uid: 1000
    shell: /bin/bash
    state: present

- name: copy sudoers_phab
  copy:
    src: files/sudoers_phab
    dest: /etc/sudoers.d/phab
    owner: root
    group: root
    mode: 0440
